//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmacy.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class tblMedication
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblMedication()
        {
            this.tblSalesDetails = new HashSet<tblSalesDetail>();
        }

        [Display(Name = "Item ID")]
        public int ItemID { get; set; }
        [Display(Name = "Item Name")]
        public string ItemName { get; set; }
        [Display(Name = "Dosage")]
        public string Dosage { get; set; }
        [Display(Name = "Price")]
        [DataType(DataType.Currency)]
        public Nullable<double> Price { get; set; }
        [Display(Name = "Expiry Date")]
        [DataType(DataType.DateTime)]
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        [Display(Name = "Prescription Required")]
        public string PrescriptionRequired { get; set; }
        [Display(Name = "Stock Quantity")]
        public Nullable<int> StockQuantity { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSalesDetail> tblSalesDetails { get; set; }
    }
}
