//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmacy.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class tblSale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSale()
        {
            this.tblSalesDetails = new HashSet<tblSalesDetail>();
        }

        [Display(Name = "Sales ID")]
        public int SalesID { get; set; }
        [Display(Name = "Customer ID")]
        public Nullable<int> CustomerID { get; set; }
        [Display(Name = "Sales Number")]
        public string SalesNumber { get; set; }
        [Display(Name = "Sales Date")]
        public Nullable<System.DateTime> SalesDate { get; set; }
        [Display(Name = "Final Total")]
        [DataType(DataType.Currency)]
        public Nullable<decimal> FinalTotal { get; set; }
    
        public virtual tblCustomer tblCustomer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSalesDetail> tblSalesDetails { get; set; }
    }
}
